backend/api/urls.py
from rest_framework import routers
from django.urls import path, include

import api.InnRequestViews
import api.PostHandlerViews
import api.adminviews
import api.views
from api import views
from rest_framework.authtoken import views as rest_views

router = routers.DefaultRouter()
router.register(r'inbox', api.PostHandlerViews.InboxApiView)
router.register(r'outbox', api.PostHandlerViews.OutboxApiView)
router.register(r'sender', views.SenderApiView)
router.register(r'manager', views.ManagerApiView)
router.register(r'profile', views.ProfileApiView)
router.register(r'role', views.RoleApiView)
router.register(r'customer', views.CustomerApiView)
router.register(r'organisation', views.OrganisationApiView)
router.register(r'type_letter', views.TypeLetterApiView)
router.register(r'send_status', views.SendStatusApiView)
router.register(r'type_work', views.TypeWorkApiView)
router.register(r'contract', views.ContractApiView)
router.register(r'status', views.StatusApiView)
router.register(r'task_status', views.TaskStatusApiView)
router.register(r'event_type', views.EventTypeApiView)
router.register(r'main_work', views.MainWorkApiView)
router.register(r'task', views.TaskApiView)
router.register(r'message', views.MessageApiView)
router.register(r'type_customer', views.TypeCustomerApiView)
router.register(r'city_type', views.CityTypeApiView)
router.register(r'street_type', views.StreetTypeApiView)
router.register(r'type_lift', views.TypeLiftApiView)
router.register(r'lift_design', views.LiftDesignApiView)
router.register(r'type_protocol', views.TypeProtocolApiView)
router.register(r'device_set', views.DeviceSetApiView)
router.register(r'status_device', views.StatusDeviceApiView)
router.register(r'type_device', views.TypeDeviceApiView)
router.register(r'range_measure', views.RangeMeasureApiView)
router.register(r'accuracy', views.AccuracyClassApiView)
router.register(r'object', views.ObjectApiView)
router.register(r'protocol', views.ProtocolApiView)
router.register(r'device', views.DeviceApiView)
router.register(r'form', views.FormApiView)
router.register(r'table', views.TableApiView)
router.register(r'lead', views.LeadApiView, basename='lead')
router.register(r'user', views.UserApiView)

# app_name = 'restapi'
urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),
    path('api/', include (router.urls), name='api'),
    path('inbox/decline/<int:inbox>/', api.PostHandlerViews.InboxDeclineView.as_view(), name='inboxDecline'),
    path('inbox/accept/<int:inbox>/', api.PostHandlerViews.InboxAcceptView.as_view(), name='inboxAccept'),
    # path('api-token-auth/', rest_views.obtain_auth_token),
    path('api-token-auth/', api.adminviews.CustomApiLoginView.as_view()),
    path('api/innrequest/', api.views.InnRequestView.as_view()),
    path('api/bankrequest/', api.views.BankRequestView.as_view()),
    path('template/', views.TemplateView.as_view(), name='template'),
    path('contract/create_by_inbox/<int:inbox>/', views.CreateContractByInboxView.as_view(), name="ContractByInbox"),
    path('get_blank/', views.GetBlankView.as_view()),
    path('forms/', views.FormsView.as_view(), name='template'),
    path('api/workrequest/<int:contract>/', views.WorkRequestView.as_view(), name='newWorkRequest'),
    path('api/workrequest/', views.WorkRequestListView.as_view(), name='WorkRequestList'),
    path('api/testfilefield/', views.FileFieldTestView.as_view(), name='FileFieldTest'),
    path('api/apps/', api.adminviews.AppView.as_view(), name='AppList'),
    path('lead/send_request/<int:lead>/', api.views.SendRequestView.as_view(), name='send_request'),
    path('lead/send_contract/<int:lead>/', api.views.SendContractView.as_view(), name='send_contract')
]

backend/project_root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from project_root.views import MainPageView

urlpatterns = [
    path('', include('api.urls')),
    path('admin/', admin.site.urls),
    path('main/', MainPageView.as_view())
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +\
    static("/", document_root='../frontend/dist/')

backend/organisation/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid

class TypeOrganisation(models.Model):
    name = models.CharField("Тип организации", max_length=255)

    def __str__(self):
        return self.name


class ChoiceName(models.Model):
    name = models.CharField("Имя поля", max_length=255)

    def __str__(self):
        return self.name


class FormType(models.Model):
    name = models.CharField("Программа обследования", max_length=255)

    def __str__(self):
        return self.name


class Element(models.Model):
    name = models.CharField("Контролируемый элемент", max_length=255)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField("Вид контроля", max_length=255)

    def __str__(self):
        return self.name


class CityType(models.Model):
    name = models.CharField("Вид населенного пункта", max_length=255)

    def __str__(self):
        return self.name


class StreetType(models.Model):
    name = models.CharField("Вид улицы", max_length=255)

    def __str__(self):
        return self.name


class TypeLift(models.Model):
    name = models.CharField("Вид улицы", max_length=255)

    def __str__(self):
        return self.name


class LiftDesign(models.Model):
    name = models.CharField("Вид улицы", max_length=255)

    def __str__(self):
        return self.name


class TypeProtocol(models.Model):
    name = models.CharField("Тип протокола", max_length=25)

    def __str__(self):
        return self.name


class DeviceSet(models.Model):
    name = models.CharField("Набор инструментов", max_length=25)

    def __str__(self):
        return self.name


class StatusDevice(models.Model):
    name = models.CharField("Статус устройства", max_length=25)

    def __str__(self):
        return self.name


class TypeDevice(models.Model):
    name = models.CharField("Тип устройства", max_length=25)

    def __str__(self):
        return self.name


class RangeMeasure(models.Model):
    name = models.CharField("Тип устройства", max_length=25)

    def __str__(self):
        return self.name


class AccuracyClass(models.Model):
    name = models.CharField("Класс точности", max_length=25)

    def __str__(self):
        return self.name


class Organisation(models.Model):
    inn = models.BigIntegerField(help_text="ИНН")
    inn_filial = models.BigIntegerField(help_text="ИНН филиала", blank=True, null=True)
    full_name = models.CharField(help_text="Полное название организации", max_length=255)
    type_customer = models.ForeignKey(TypeOrganisation, on_delete=models.CASCADE, help_text="Тип клиента")
    head = models.CharField(help_text="Должность руководителя",  max_length=100)
    head_name = models.CharField(help_text="Имя руководителя",  max_length=50)
    head_surname = models.CharField(help_text="Отчество руководителя",  max_length=50)
    head_last_name = models.CharField(help_text="Фамилия руководителя", max_length=50)
    kpp = models.BigIntegerField(help_text="КПП", blank=True, null=True)
    ogrn = models.BigIntegerField(help_text="ОГРН", null=True)
    bank = models.CharField(help_text="Наименование банка", max_length=200, blank=True, null=True)
    account = models.BigIntegerField(help_text="Расчетный счет", blank=True, null=True)
    cor_account = models.BigIntegerField(help_text="Кор.счёт", blank=True, null=True)
    bic = models.IntegerField(help_text="БИК", blank=True, null=True)
    phone = models.BigIntegerField(blank=True, null=True, help_text='Телефон')
    add_phone = models.BigIntegerField(blank=True, null=True, help_text='Доп. телефон')
    fax = models.BigIntegerField(blank=True, null=True, help_text="Факс")
    filial_count = models.SmallIntegerField(help_text="Кол-во филииалов", blank=True, null=True)
    legal_address = models.CharField(max_length=500, help_text="Юридический адрес", blank=True, null=True)
    post_address = models.CharField(max_length=500, help_text="Почтовый адрес", blank=True, null=True)

    def __str__(self):
        return self.full_name


class Object(models.Model):
    postcode = models.IntegerField("Почтовый индекс")
    region = models.CharField("Регион", max_length=100)
    city_type = models.ForeignKey(CityType, on_delete=models.CASCADE, verbose_name="Вид населенного пункта")
    city = models.CharField("Город", max_length=100)
    street_type = models.ForeignKey(StreetType, models.CASCADE, verbose_name="Вид улицы")
    street = models.CharField("Название",  max_length=100)
    building = models.CharField("Корпус", blank=True, null=True, max_length=50)
    entrance = models.IntegerField("Номер подъезда", blank=True, null=True,)
    office = models.CharField("Номер офиса", blank=True, null=True, max_length=25)
    lifts_count = models.SmallIntegerField("Кол-во лифтов", blank=True, null=True)
    reg_num = models.CharField("Регистрационный номер", max_length=25, blank=True, null=True)
    mf_year = models.DateField("Год выпуска", blank=True, null=True)
    type_lift = models.ForeignKey(TypeLift, on_delete=models.PROTECT, blank=True, null=True, verbose_name="Тип лифта")
    capacity = models.DecimalField("Грузоподъемность", blank=True, null=True, max_digits=7, decimal_places=2)
    floors = models.SmallIntegerField("Кол-во этажей", blank=True, null=True)
    speed = models.DecimalField("Скорость лифта", blank=True, null=True, max_digits=6, decimal_places=3)
    maker = models.CharField("Производитель", max_length=100, blank=True, null=True)
    serial_number = models.CharField("Серийный номер", max_length=100, blank=True, null=True)
    date_exam = models.DateField("Дата проверки", blank=True, null=True)
    lift_design = models.ForeignKey(LiftDesign, models.CASCADE, verbose_name="Дизайн лифта", blank=True, null=True)
    freq = models.SmallIntegerField("частота", blank=True, null=True)
    auto_door = models.SmallIntegerField("Автоматические двери", blank=True, null=True)
    num_lines = models.SmallIntegerField("Кол-во линий", blank=True, null=True)
    customer = models.ForeignKey(Organisation, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return "{} {} {}".format(self.city,self.street, self.building)


class Form(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование формы")

    def __str__(self):
        return "{}".format(self.name)


class Protocol(models.Model):
    type_protocol = models.ForeignKey(TypeProtocol, on_delete=models.PROTECT, verbose_name="Тип протокола", null=True)
    num = models.CharField(max_length=25, verbose_name="Номер протокола", null=True)
    date_act = models.DateField(verbose_name="Год регистрации", auto_now=True)
    date_protocol = models.DateField(verbose_name="Год регистрации", auto_now=True)
    customer = models.ForeignKey(Organisation, on_delete=models.PROTECT, related_name="customer", verbose_name="Заказчик", null=True)
    owner = models.ForeignKey(Organisation, on_delete=models.PROTECT, related_name="owner", verbose_name="Собственник", null=True)
    worker = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Исполнитель", related_name="user", null=True)
    device_set = models.ForeignKey(DeviceSet, on_delete=models.PROTECT, verbose_name="Набор инструментов", null=True)
    customer_person = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name="Контактное лицо заказчика",
        related_name="customer_person",
        null = True
    )
    owner_person = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name="Контактное лицо собственника",
        related_name="owner_person",
        null=True
    )
    form = models.ForeignKey(Form, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return "{} от {}".format(self.num, self.date_act)


class Device(models.Model):
    name = models.CharField("Наименование прибора", max_length=50)
    type_device = models.ForeignKey(TypeDevice, on_delete=models.PROTECT, verbose_name="Тип прибора")
    serial_number = models.CharField("Серийный номер", max_length=25)
    state_reg = models.CharField(max_length=25)
    range_measure = models.ForeignKey(RangeMeasure, on_delete=models.PROTECT)
    accuracy_class = models.ForeignKey(AccuracyClass, on_delete=models.PROTECT)
    verify_number = models.CharField(max_length=25)
    verify_date = models.DateField(auto_now=True, verbose_name="Дата последней поверки")
    next_verify = models.DateField(verbose_name="Дата следующей поверки")
    period_verify = models.DurationField(verbose_name="Период поверки")
    certification_center = models.CharField(verbose_name="Сертификационный центр", max_length=25)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    device_set = models.ForeignKey(DeviceSet, on_delete=models.PROTECT)
    maker = models.CharField(max_length=50, verbose_name="Производитель")
    status = models.ForeignKey(StatusDevice, on_delete=models.PROTECT, verbose_name="Статус устройства")

    def __str__(self):
        return "{} от {} {}".format(self.num, self.date_act, self.object_exam)


class Document(models.Model):
    name = models.CharField(max_length=255, verbose_name="Документ")

    def __str__(self):
        return "{}".format(self.name)


class Reason(models.Model):
    document = models.ForeignKey(Document, on_delete=models.PROTECT)
    point = models.CharField(max_length=25,verbose_name="Номер пункта")
    phrasing = models.TextField()

    def __str__(self):
        return "Док. {} п. {}".format(
            self.document,
            self.point)


class DefectList(models.Model):
    reason = models.ForeignKey(Reason, on_delete=models.PROTECT, verbose_name="Документ", null=True)
    phrasing = models.TextField()

    def __str__(self):
        return "Док. {} п. {}".format(
            self.reason.document.name,
            self.phrasing
        )


class Table(models.Model):

backend/templates/TaskDetail.html
{% extends "basePage.html" %}
{% load static %}

{% block contentHeader %}
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-12s">
            <h1 class="m-0 text-dark">{{header}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Выбери заявку для обработки</h3>

            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 250px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Поиск по заявкам">

                <div class="input-group-append">
                  <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0" style="height: 100%;">
            {{ object.title }}
              {{ object.content }}
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
<div class="container-fluid">
</div>
{% endblock %}

{% block controlScripts %}
<script src="{% static 'js/cookies/jquery.cookie.js' %}"></script>
<script src="{% static "js/menuControl.js" %}"></script>
{% endblock controlScripts %}

backend/templates/TaskList.html
{% extends "basePage.html" %}
{% load static %}

{% block contentHeader %}
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-12s">
            <h1 class="m-0 text-dark">{{header}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Выбери заявку для обработки</h3>

            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 250px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Поиск по заявкам">

                <div class="input-group-append">
                  <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0" style="height: 100%;">
            <table class="table table-head-fixed text-nowrap">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>User</th>
                  <th>Date</th>
                  <th>Status</th>
                  <th>Reason</th>
                </tr>
              </thead>
              <tbody>
              {% for task in object_list %}
                <tr>
                  <td>{{ task.id }}</td>
                  <td>{{ task.initiator.username }}</td>
                  <td>{{ task.initiator.username }}</td>
                  <td>{{ task.executor.username }}</td>
                  <td>{{ task.title }}</td>
                  <td>{{ task.content }}</td>
                  <td><a href="{% url 'works:task-detail' task.id %}">{{ task.status }}</a></td>
                  <td>{{ task.work_flow.inbox.customer.full_name }}</td>
                </tr>
              {% empty %}
                Нет необработанных задач
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="pagination">
            <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; Первая</a>
                  <a href="?page={{ page_obj.previous_page_number }}"> << </a>
              {% endif %}

              <span class="current">
                  Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
              </span>

              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}"> >> </a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
              {% endif %}
            </span>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
<div class="container-fluid">
</div>
{% endblock %}

{% block controlScripts %}
<script src="{% static 'js/cookies/jquery.cookie.js' %}"></script>
<script src="{% static "js/menuControl.js" %}"></script>
{% endblock controlScripts %}

backend/templates/basePage.html
{% extends "base.html" %}
{% load static %}

{% block navbar %}
{% for section in menu.sections %}
    {% if section.is_active == True %}
        {% include "navbar.html" with menu=section.menu %}
    {% endif %}
{% endfor %}
{% endblock %}

{% block mainSider %}
{% include "mainSider.html" %}
{% endblock %}

backend/templates/form.html
{% csrf_token %}
{{ form.as_p }}

backend/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <title>{{title}}</title>
</head>
<body>
    Home page
</body>
</html>

backend/templates/inlineForm.html
{% extends "basePage.html" %}
{% load static %}

{% block contentHeader %}
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-12s">
            <h1 class="m-0 text-dark">{{header}}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6 left-form">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">{{ form_header }}</h3>
        </div>
        <div class="card-body">
          <!-- /.card-header -->
          <!-- form start -->
          <form method="post" enctype="multipart/form-data" id="MainForm">
            {% include "form.html" %}
          <!-- /.card-body -->
          </form>
          <div class="card-footer">
            <input form="MainForm" type="submit" value="Зарегистрировать" class="btn btn-primary">
          </div>
        </div>
      </div>
      <!-- /.card -->
    </div>
    <div class="col-md-6 right-form" style="display:none;">

    </div>
  </div>
</div>
{% endblock %}

{% block controlScripts %}
<script src="{% static 'js/cookies/jquery.cookie.js' %}"></script>
<script src="{% static "js/menuControl.js" %}"></script>
{% endblock controlScripts %}

backend/templates/mainSider.html
{% load static %}
<!-- Sidebar user panel (optional) -->
<div class="user-panel mt-3 pb-3 mb-3 d-flex align-items-center">
    <div class="image">
        <img src="{% static "admlte3/dist/img/user2-160x160.jpg" %}" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
        <a href="#" class="d-block"> {{ user.first_name }} {{ user.profile.surname }} {{ user.last_name }}</a>
    </div>
</div>

    <!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
        with font-awesome or any other icon font library -->
        {% for section in menu.sections %}
        <li class="nav-item">
        <a href="{% url section.url %}?id={{ forloop.counter0 }}" class="nav-link {% if section.is_active %} active {% endif %}">
            <i class="{{section.icon }} nav-icon"></i>
            <p> {{ section.name }}  </p>
        </a>
        {% endfor %}
        </li>
    </ul>
</nav>
<!-- /.sidebar-menu -->

backend/templates/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      {% for item in menu %}
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url item.url %}" class="nav-link">{{ item.name }}</a>
      </li>
      {% endfor %}
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "admlte3/dist/img/user1-128x128.jpg" %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "admlte3/dist/img/user8-128x128.jpg" %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static "admlte3/dist/img/user3-128x128.jpg" %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-slide="true" href="/logout" role="button">
            <i class="fas fa-sign-out-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

backend/templates/ok.html
Объект успешно сохранен в базе
<input type="hidden" id="obj" value="{{obj.id}}">

backend/templates/single_form.html
<!-- right column -->
<!-- general form elements -->
<div class="card card-info">
  <div class="card-header">
    <h3 class="card-title">{{ form_header }}</h3>
  </div>
   <div class="card-body">
    <!-- /.card-header -->
    <!-- form start -->
    <form method="post" action="{% url form.action %}" class="second-form">
    {% csrf_token %}
    {{ form }}
      <!-- /.card-body -->
      <div class="card-footer">
        <input type="hidden" name="form_class" value="{{form_class}}">
        <input type="button" class="btn btn-warning cancel" value="Отменить">
        <input type="submit" class="btn btn-primary send-form" value="Отправить">
      </div>
    </form>
  </div>
</div>
<!-- /.card -->